name: ai_financial_manager
description: messenger app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio:
  easy_localization:
  flutter:
    sdk: flutter
  flutter_bloc:
  fluttertoast: ^8.2.2
  freezed_annotation:
  get_it: ^7.6.0
  injectable: ^2.2.0
  internet_connection_checker_plus: ^2.0.0
  intl:
  shared_preferences: ^2.2.0
  styled_widget: ^0.4.1
  auto_route: ^8.3.0
  flutter_svg: ^2.0.7
  image_picker: ^0.8.6
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.7
  jwt_decoder: ^2.0.1
  firebase_core:
  firebase_messaging: ^14.7.8
  flutter_screenutil: ^5.8.4
  flutter_riverpod: ^2.3.7
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1 # contains Isar Core
  permission_handler: ^10.4.3
  simple_animations: ^5.0.2
  collection: ^1.17.1
  flutter_keyboard_visibility: ^5.4.1
  share_plus: ^7.1.0
  flutter_dialogs: ^3.0.0
  geolocator: ^11.1.0
  firebase_vertexai: ^0.1.1
  equatable: ^2.0.5
  uuid: ^4.4.2

dev_dependencies:
  analyzer:
  isar_generator:
  auto_route_generator:
  build_runner:
  flutter_launcher_icons: ^0.13.1
  flutter_lints:
  flutter_native_splash: ^2.4.0
  freezed:
  injectable_generator:
  logger:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf

flutter_native_splash:
  color: "#1C1F2B"
  image: assets/images/ai_financial_manager_x4.png
  # color_dark: "#3595D3"
  # image_dark: assets/images/dark_splash.png
  android_12:
    image: assets/images/ai_financial_manager_android12.png
    color: "#1C1F2B"
    # color_dark: "#3595D3"
  fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ai_financial_manager_icon.png"
  remove_alpha_ios: true

flutter_assets:
  assets_path: assets/
  output_path: lib/core/UI/styles/
  filename: assets.dart
